name: Terraform Workflow

on:
  push:
    branches:
      - testing
  pull_request:
    branches:
      - testing
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform cleanup'
        type: choice
        options:
          - cleanup
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_LOG: DEBUG
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Decode Google Cloud credentials
        run: echo "${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}" | base64 -d > service-account-key.json

      - name: Set GOOGLE_APPLICATION_CREDENTIALS
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=service-account-key.json" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: terraform init

      - name: Run terraform fmt check
        run: terraform fmt -check

      - name: Run terraform validate
        run: terraform validate

      - name: Run terraform plan
        run: terraform plan -out=tfplan

      - name: Upload tfplan file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

  apply:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Download tfplan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: .

      - name: Decode Google Cloud credentials
        run: echo "${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}" | base64 -d > service-account-key.json

      - name: Set GOOGLE_APPLICATION_CREDENTIALS
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=service-account-key.json" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: terraform init

      - name: Run terraform apply
        run: terraform apply -auto-approve tfplan

  cleanup:
    runs-on: ubuntu-latest
    needs: apply
    if: ${{ github.event.inputs.action == 'cleanup' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Decode Google Cloud credentials
        run: echo "${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}" | base64 -d > service-account-key.json

      - name: Set GOOGLE_APPLICATION_CREDENTIALS
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=service-account-key.json" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: terraform init

      - name: Run terraform destroy
        run: terraform destroy -auto-approve
